### ISSUE TITLE
Profile doesn't save with reassigned profile buttons

### ISSUE THREAD

**Issue by Koltsifer** [Strobel273/InventiveInventory#28]
Mod Version 0.4.2 & Minecraft Fabric 1.20.6

When you reassign profile buttons to anything rather numbers, the profiles are no longer saved; when you try to load a profile, the game writes that "Profile for keybind 'n' not found"

Also it would be great if there was fast loading, just with one button.

![изображение](https://github.com/Strobel273/InventiveInventory/assets/56967355/072ba731-4b91-4dcc-8a9d-c5f29058b61b)

**Comment by Strobel273** [comment]
Hey there,
thank you for your report.

We were able to reproduce the issue and will work on it.

For you request of just using one key to load a profile, we have something in mind to implement this functionality and hope to introduce it along the bug fix in a new version.

Thanks again
Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey there,
the bug is now fixed along a few others which showed up during the process.

Additionally, we have implemented your feature suggestion "Profile Fast Loading". You can switch between Standard and Fast Loading Modes for every individual Profile via the Config Screen through the Mod Menu Mod (or in the config folder).

Thank you again and have fun with our mod.
Your Inventive Inventory Team
