### ISSUE TITLE
Modify Sorting Mode Option

### ISSUE THREAD

**Issue by Havixxi** [Strobel273/InventiveInventory#34]
**Mod Version & Minecraft Version**
0.4.4 - 1.21 Fabric

**Describe the feature**
Specify how to change the sorting mode.
Please add in-game or a in a config file the specefic value that modifies the sorting mode. I want to sort my items by item type but in the "settings" config file, i could not change correctly the SortingMode value because nowhere is the correct value specified. I tried several times writting "Type", "Item", "ItemType", etc but i doesn't work.
Maybe it is mine beginner mistake but it would help a lot a in-game option that changes the sorting mode or a hint in the config file.
Also, im writting this by Google Translate in case there any errors.

Thanks for reading, greetings from Chile.

**Comment by Strobel273** [comment]
Hey there,
Actually we have a config screen implemented using the Mod Menu Integration. So if you want to change the configs directly in the game you have to install [ModMenu](https://modrinth.com/mod/modmenu).

Otherwise you can change the configs in the config file as you tried but you have to type **"Item Type"** with a whitespace. We know that this is not ideal and right now we are working on our official release version 1.0.0 which will include commands to change the mod configs and hopefully eliminate such ambiguities.

I hope I could help. 
If you still experience a problem, just let us know.

Your Inventive Inventory Team
