### ISSUE TITLE
Refill tools 

### ISSUE THREAD

**Issue by elnoelsi** [Strobel273/InventiveInventory#37]
**Mod Version & Minecraft Version**
latest

**Describe the feature**
Pretty self explanatory. Just like with blocks but with tools if you have any in your inventory (perhaps not including hotbar)

Also on a sidenote i think the name "inverted" for the fill feature should be renamed, very confusing. I would suggest something like "Automatic". 

Refilling Mode: Automatic and Standard/Semi-Automatic. 

By default its not truly automatic so calling the feature itself automatic doesnt make much sense to me.

Anyway, thanks a lot for the mod, its pretty much all i need and wanted, IPN is so bloated nowdays and feels buggy.

**Comment by Strobel273** [comment]
Hey elnoelsi,
thank you very much for your suggestions.

We like the idea of broken tools getting swapped as well as blocks.
Also changing the mode names to a more describing name would surly make sense.

We will definitely consider your ideas and will pair them with our own imaginations.

Thanks again for your input,
Your Inventive Inventory Team

**Comment by elnoelsi** [comment]
Rockets would be amazing too :)

**Comment by elnoelsi** [comment]
Potions aswell....

**Comment by Strobel273** [comment]
We will take these into account as well of course.
Thank you very much!

**Comment by Strobel273** [comment]
Hey there, 
we have finally released our 1.0.0 version.
A load of new features and changes made the way in our mod. You can view the official changelog on Modrinth or our [Discord](https://discord.gg/uycTMfCsfc ).
We are happy with how it turned out and we hope it meets your requirements.

If anything doesn't work correctly please let us know via our [Discord](https://discord.gg/uycTMfCsfc ) or Github Issue.
(Note that we moved our repository to our [Organization Account](https://github.com/Origins-Tech/InventiveInventory))

Your Inventive Inventory Team
