### ISSUE TITLE
Option to enable refilling in offhand 

### ISSUE THREAD

**Issue by elnoelsi** [Strobel273/InventiveInventory#39]
I imagine there is a reason or a matter of preference to why offhand doesnt get refilled but an option to enable it would be great.

**Comment by Strobel273** [comment]
Hey there,
it is in fact a bit tricky but we managed to implement that and will release this also in our official release version.
Nice Idea, thank you!

Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey there, 
we have finally released our 1.0.0 version.
A load of new features and changes made the way in our mod. You can view the official changelog on Modrinth or our [Discord](https://discord.gg/uycTMfCsfc ).
We are happy with how it turned out and we hope it meets your requirements.

If anything doesn't work correctly please let us know via our [Discord](https://discord.gg/uycTMfCsfc ) or Github Issue.
(Note that we moved our repository to our [Organization Account](https://github.com/Origins-Tech/InventiveInventory))

Your Inventive Inventory Team
