### ISSUE TITLE
Automatic Refilling not working after item is used？

### ISSUE THREAD

**Issue by Narase-Edge** [Strobel273/InventiveInventory#40]
**Mod Version & Minecraft Version**
Inventive Inventory 0.4.6, Minecraft Version 1.21

**Describe the bug**
When I eat the last item, the auto-replenishment doesn't work, but when I discard it, the auto-replenishment works fine. Is this expected?

**Comment by Strobel273** [comment]
Hey there,
thank you for your report.

We are already aware of this issue and will release a fix as a part of our official release version.
We hope to publish it this week.

Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey there, 
we have finally released our 1.0.0 version.
A load of new features and changes made the way in our mod. You can view the official changelog on Modrinth or our [Discord](https://discord.gg/uycTMfCsfc ).
We are happy with how it turned out and we hope it meets your requirements.

If anything doesn't work correctly please let us know via our [Discord](https://discord.gg/uycTMfCsfc ) or Github Issue.
(Note that we moved our repository to our [Organization Account](https://github.com/Origins-Tech/InventiveInventory))

Your Inventive Inventory Team
